#!/bin/bash

export PATH=./node_modules/.bin:$PATH

function build(){
    rm -fr dist || true
    node scripts/build.cjs
}

function ci(){

    function keybase(){
        git config --global user.email "deploys@vellajs.org"
        git config --global user.name "Deploy Bot"
        # You'll need the paper key in order for this to work in CI
        keybase oneshot
        git clone keybase://team/vella/secrets secrets
    }

    function deploy(){
        build
        $(npm bin)/rollup -c rollup.docs.js
        pushd dist/docs
        source vella-secrets/.env
        export AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY
        aws s3 sync . s3://vellajs.org --delete
        aws s3 cp index.html s3://vellajs.org/index.html
        popd
    }

    eval "$@"
}


function lint(){
    eslint . --cache
}

function test(){
    ospec
}

eval "$@"